version: '2.1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123
    restart: always
    volumes:
    - vmssql:/var/opt/mssql
  
  asp:
    image: aspnetdemo3
    restart: always
    build: ./
    ports:
      - 80:80
    links:
      - sqlserver

volumes:
  vmssql: